### ISSUE TITLE
Package should belongs to JuliaIO

### ISSUE THREAD

**Issue by o314** [dcjones/Codecs.jl#31]
Hello BioJulia,

I'm fighting with entropy in the Julia world those days. It's becoming very,
very hard to know where to grasp a recommended / authoritative package among
Julia ones, even in 2019.

Doesn't this package would be better hosted at
[JuliaIO](http://github.com/JuliaIO) so anyone concerned would
find it easily ?

Thanks

**Comment by randyzwitch** [comment]
The organization where a package is held is somewhat arbitrary; while in many cases, it indicates the overall concept of related packages, on GitHub it also indicates a permission level. In this case, several people as part of BioJulia rely on Codecs.jl, so it was moved here.

Package discovery is still an open issue, but it's probably better handled more globally with some of the discussions that happen on Slack/Discourse around Julia Observer or pkg.julialang.org or a similar website, rather than shuffling the packages around on GitHub.
